CRS = "EPSG:4326"

INDEX_BAND_MAPPER: dict[int, dict[str, list[str]]] = {
    1: {  # слои для снимков L1C
        "ndvi": ["nir", "red"],
        "cndvi": ["nir", "red"],
        "gndvi": ["nir", "green"],
        "ndmi": ["nir", "swir1"],
        "evi": ["nir", "red", "blue"],
        "cvi": ["nir", "red", "green"],
        "bai": ["red", "nir"],
        "lai_savi": ["red", "nir"],
        "msavi2": ["red", "nir"],
        "nbr": ["nir", "swir2"],
        "ndwi": ["nir", "green"],
        "mndwi": ["green", "swir2"],
        "mcari": ["green", "red", "rededge1"],
        "bsi": ["blue", "red", "nir", "swir1"],
        "cloud": [],
        "shadow": [],
        "blue": ["blue"],
        "green": ["green"],
        "red": ["red"],
        "nir": ["nir"],
        "swir1": ["swir1"],
        "swir2": ["swir2"],
    },
    2: {  # слои для снимков L2A
        "ndvi": ["nir", "red", "qa"],
        "cndvi": ["nir", "red", "qa"],
        "gndvi": ["nir", "green", "qa"],
        "ndmi": ["nir", "swir1", "qa"],
        "evi": ["nir", "red", "blue", "qa"],
        "cvi": ["nir", "red", "green", "qa"],
        "bai": ["red", "nir", "qa"],
        "lai_savi": ["red", "nir", "qa"],
        "msavi2": ["red", "nir", "qa"],
        "nbr": ["nir", "swir2", "qa"],
        "ndwi": ["nir", "green", "qa"],
        "mndwi": ["green", "swir2", "qa"],
        "mcari": ["green", "red", "rededge1", "qa"],
        "bsi": ["blue", "red", "nir", "swir1", "qa"],
        "cloud": ["qa"],
        "shadow": ["qa"],
        "blue": ["blue", "qa"],
        "green": ["green", "qa"],
        "red": ["red", "qa"],
        "nir": ["nir", "qa"],
        "swir1": ["swir1", "qa"],
        "swir2": ["swir2", "qa"],
    },
}

# Каналы для расчёта индексов: [band1, band2, extra_band]
INDEX_BANDS: dict[str, list[str]] = {
    "ndvi": ["nir", "red"],
    "cndvi": ["nir", "red"],
    "gndvi": ["nir", "green"],
    "ndmi": ["nir", "swir1"],
    "evi": ["nir", "red", "blue"],
    "cvi": ["nir", "red", "green"],
    "bai": ["red", "nir"],
    "lai_savi": ["red", "nir"],
    "msavi2": ["red", "nir"],
    "nbr": ["nir", "swir2"],
    "ndwi": ["nir", "green"],
    "mndwi": ["green", "swir2"],
    "mcari": ["green", "red", "rededge1"],
    "bsi": ["blue", "red", "nir", "swir1"],
    "cloud": ["qa", "qa"],
    "shadow": ["qa", "qa"],
    "blue": ["blue"],
    "green": ["green"],
    "red": ["red"],
    "nir": ["nir"],
    "swir1": ["swir1"],
    "swir2": ["swir2"],
}

CLASS_NAME = {
    0: {"name": "burns", "threshold": 0.25},
    1: {"name": "deforestation", "threshold": 0.5},
    2: {"name": "drying", "threshold": 0.75},
    3: {"name": "windfalls", "threshold": 1},
}
